project:
  type: website
  output-dir: docs

website:
  title: "Fletcher McConnell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: spacelab
      dark: zephyr
    css: styles.css
    toc: true
    page-layout: full
    
    editor: visual



