project:
  type: website
  output-dir: docs

website:
  title: "Fletcher McConnell" # title: false, then logo: image to have a logo instead of name in upper left
  navbar:
    favicon: fletcher_photo.jpg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - blog.qmd
      - href: Resume/fletcher_mcconnell_resume.pdf
        text: Resume
    right: 
      - icon: github
        href: https://github.com/fletcher-m
      - icon: envelope
        href: mailto::fletcher.mcconnell@outlook.com
      - icon: linkedin
        href: https://www.linkedin.com/in/fletcher-mcconnell-253894294/
  page-footer: 
    background: light
    left: "Copyright 2023, Fletcher McConnell"
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/fletcher-m/fletcher-m.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
format:
  html:
    theme: styles.scss
   # css: styles.css
    mainfont: Kanit
    toc: true
    page-layout: full
    
    editor: visual



